- hosts: all
  vars:
    extra_args: "-i https://pypi.tuna.tsinghua.edu.cn/simple"
  collections:
   - yhydev.deploy_docker
  roles:
  - role: mirrors
  - role: darkwizard242.python3
  - role: geerlingguy.pip
  - role: install-pppoe-api
  - role: init-docker-daemon
  - role: install-docker
  - role: enable-docker
  - role: deploy-goproxy-container