- name: Pip Install docker
  pip: name=docker executable=pip3.6 extra_args="{{ pip_extra_args }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
- name: deploy goproxy
  community.docker.docker_container:
    name: goproxy
    state: started
    image: 40up3346.mirror.aliyuncs.com/c18s/goproxy
    command: proxy socks -t tcp -p 0.0.0.0:1080 --dns-address "121.4.173.6:53"
    ports:
    - 1080:1080
  vars:
    ansible_python_interpreter: /usr/bin/python3
- name: deploy goproxy http proxy
  community.docker.docker_container:
    name: goproxy-http
    state: started
    image: 40up3346.mirror.aliyuncs.com/c18s/goproxy
    command: proxy http -t tcp -p "0.0.0.0:1080"
    ports:
    - 2080:1080
  vars:
    ansible_python_interpreter: /usr/bin/python3